general:
  debugMode: true
cannonLimits:
  useLimits: true
  buildLimitA: 1
  buildLimitB: 100
tools:
  ajust: '0:0'
  autoaim: '347:0'
  rotatingItem: '350:0'
database:
  username: bukkit
  password: walrus
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:{DIR}{NAME}.db
  rebuild: false