name: Cannons
main: at.pavlov.Cannons.CannonPlugin
version: 1.9.3
author: Pavlov
description: >
             A small plugin to fire cannons which are build out of blocks.
commands:
  cannons:
    description: Info how to use/build/adjust a cannon and to reload the plugin.

permissions:
  cannons.*:
    description: Gives single permissions for loading, adjusting, firing and recall help with cannons
      children:
        cannons.player.*: true
        cannons.admin.*: true
        cannons.projectile.*: true
  
  cannons.player.*:
    description: Gives single permissions for loading, adjusting, firing and recall help with cannons
    children:
      cannons.player.load: true
      cannons.player.adjust: true
      cannons.player.fire: true
      cannons.player.command: true
      cannons.player.placeRedstoneTorch: true
      cannons.player.limitA: false
      cannons.player.limitB: false
  cannons.admin.*:
    description: Gives all admin rights
    children:
      cannons.admin.reload: true   
  cannons.projectile.*:
    description: Gives the right for all projectiles
    children:
      cannons.projectile: true
      
  cannons.player.load:
      description: Allows a player to load a cannon
      default: true
  cannons.player.adjust:
      description: Allows a player to adjust a cannon
      default: true  
  cannons.player.fire:
      description: Allows a player to fire a cannon
      default: true
  cannons.player.limitA:
      description: Maximum amount of cannons a player can place
      default: false
  cannons.player.limitB:
      description: Maximum amount of cannons a player can place
      default: false
  cannons.player.command:
      description: Allows a player to request help with a cannon
      default: true
  cannons.player.placeRedstoneTorch:
      description: Allows a player to place redstone torch under a cannon
      default: op  
  cannons.admin.reload:
      description: Allows a player to reload the config
      default: op
  cannons.projectile:
      description: Right to load all projectiles
      default: true
  
