name: Cannons
main: at.pavlov.Cannons.Cannons
version: 1.9.5
author: Pavlov
description: >
             A small plugin to fire cannons which are build out of blocks.
commands:
  cannons:
    description: Info how to use/build/adjust a cannon and to reload the plugin.

permissions:
  cannons.*:
    description: Gives single permissions for loading, adjusting, firing and recall help with cannons
    children:
      cannons.player.*: true
      cannons.admin.*: true
      cannons.projectile.*: true
  
  cannons.player.*:
    description: Gives single permissions for loading, adjusting, firing and recall help with cannons
    children:
      cannons.player.load: true
      cannons.player.adjust: true
      cannons.player.fire: true
      cannons.player.help: true
      cannons.player.reset: true
      cannons.player.placeRedstoneTorch: true
  cannons.admin.*:
    description: Gives all admin rights
    children:
      cannons.admin.reload: true   
  cannons.projectile.*:
    description: Gives the right for all projectiles
    children:
      cannons.projectile: true
      
  cannons.player.load:
      description: Allows a player to load a cannon
      default: false
  cannons.player.adjust:
      description: Allows a player to adjust a cannon
      default: false  
  cannons.player.fire:
      description: Allows a player to fire a cannon
      default: false
  cannons.player.limitA:
      description: Maximum amount of cannons a player can place
      default: false
  cannons.player.limitB:
      description: Maximum amount of cannons a player can place
      default: false
  cannons.player.limit:
      description: Set the of cannons a player can build as number e.g. limit.5
      default: false
  cannons.player.help:
      description: Allows a player to request help with a cannon
      default: false
  cannons.player.reset:
      description: Allows a player to delete all of his build cannons.
      default: false
  cannons.player.placeRedstoneTorch:
      description: Allows a player to place redstone torch under a cannon
      default: false  
  cannons.admin.reload:
      description: Allows a player to reload the config
      default: op
  cannons.projectile:
      description: Right to load all projectiles
      default: false
  
